on: [push, pull_request]

name: Continuous integration

jobs:
  test:
    name: "Test"
    strategy:
      matrix:
        cmd: [check, fmt,clippy]
        include:
          - cmd: fmt
            args: "--all -- --check"
          - cmd: clippy
            arg: "-- -D warnings"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: ${{ matrix.cmd }}
          args: ${{ matrix.arg }}
